name: Android CI

on:
  push:
    branches: 
      - main
      - Harveer
  pull_request:
    branches: 
      - main
      - Harveer

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Decode google-services.json
      env:
        FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
      run: echo $FIREBASE_SECRET | base64 --decode > ./code/app/google-services.json

    - name: Grant execute permission for gradlew
      working-directory: ./code
      run: chmod +x gradlew

    - name: Build with Gradle
      working-directory: ./code
      run: ./gradlew build

    - name: Run Unit Tests
      working-directory: ./code
      run: ./gradlew test

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: 30.0.3

    - name: Start emulator
      run: |
          sudo apt-get update
          sudo apt-get install -y libx11-6
          sdkmanager --install "system-images;android-30;google_apis;x86_64"
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "pixel"
          $ANDROID_HOME/emulator/emulator -avd test -no-window -no-audio -no-boot-anim -gpu off &
          adb wait-for-device
          adb shell input keyevent 82
          timeout-minutes: 5
      continue-on-error: true

    - name: Run Instrumentation Tests
      working-directory: ./code
      run: ./gradlew connectedAndroidTest
      continue-on-error: true

    - name: Stop emulator
      if: always()
      run: adb -s emulator-5554 emu kill
