name: Android CI

on:
  push:
    branches: 
      - main
      - Harveer
  pull_request:
    branches: 
      - main
      - Harveer

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Decode google-services.json
      env:
        FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
      run: echo $FIREBASE_SECRET | base64 --decode > ./code/app/google-services.json

    - name: Grant execute permission for gradlew
      working-directory: ./code
      run: chmod +x gradlew

    - name: Build with Gradle
      working-directory: ./code
      run: ./gradlew build

    - name: Run Unit Tests
      working-directory: ./code
      run: ./gradlew test
